# -*- coding: utf-8 -*-
"""01_analisis_teks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-kK4EyOmzJb3ainbIin-4mIn5_ilp_p
"""

#Program 1 - Menghitung jumlah kata dan jumlah kalimat dari sebuah teks
teks = input("Masukkan teks: ").strip()

#Hitung jumlah kalimat (berdasarkan titik)
jumlah_kalimat = teks.count(".")

#Hitung jumlah kata
jumlah_kata = len(teks.split())

print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")

#Program 1 - Menghitung jumlah kata dan jumlah kalimat dari sebuah teks
teks = input("Masukkan teks: ").strip()

#Hitung jumlah kalimat (berdasarkan titik)
jumlah_kalimat = teks.count(".")

#Hitung jumlah kata
jumlah_kata = len(teks.split())

print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")

#Program 1 - Menghitung jumlah kata dan jumlah kalimat dari sebuah teks
teks = input("Masukkan teks: ").strip()

#Hitung jumlah kalimat (berdasarkan titik)
jumlah_kalimat = teks.count(".")

#Hitung jumlah kata
jumlah_kata = len(teks.split())

print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")

