# -*- coding: utf-8 -*-
"""01_analisis_teks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-kK4EyOmzJb3ainbIin-4mIn5_ilp_p
"""

#Program 1 - Menghitung jumlah kata dan jumlah kalimat dari sebuah teks

#Menerima input teks dari pengguna dan menghapus spasi di awal maupun akhir teks
teks = input("Masukkan teks: ").strip()

#Menghitung jumlah tanda titik (.) dalam teks sebagai jumlah kalimat
jumlah_kalimat = teks.count(".")

#Memisahkan teks menjadi kata-kata berdasarkan spasi, lalu menghitung jumlah katanya
jumlah_kata = len(teks.split())

#Menampilkan hasil jumlah kalimat dan jumlah kata
print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")

#Program 1 - Menghitung jumlah kata dan jumlah kalimat dari sebuah teks

#Menerima input teks dari pengguna dan menghapus spasi di awal maupun akhir teks
teks = input("Masukkan teks: ").strip()

#Menghitung jumlah tanda titik (.) dalam teks sebagai jumlah kalimat
jumlah_kalimat = teks.count(".")

#Memisahkan teks menjadi kata-kata berdasarkan spasi, lalu menghitung jumlah katanya
jumlah_kata = len(teks.split())

#Menampilkan hasil jumlah kalimat dan jumlah kata
print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")

#Program 1 - Menghitung jumlah kata dan jumlah kalimat dari sebuah teks

#Menerima input teks dari pengguna dan menghapus spasi di awal maupun akhir teks
teks = input("Masukkan teks: ").strip()

#Menghitung jumlah tanda titik (.) dalam teks sebagai jumlah kalimat
jumlah_kalimat = teks.count(".")

#Memisahkan teks menjadi kata-kata berdasarkan spasi, lalu menghitung jumlah katanya
jumlah_kata = len(teks.split())

#Menampilkan hasil jumlah kalimat dan jumlah kata
print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")