# -*- coding: utf-8 -*-
"""02_Menampilkan kalimat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1SofaLNYPGc0VK5rwxuOQAMJSiba8bI
"""

# Program 2 - Membuat objek string K1 sampai K4

K1 = "Saya tak 'kan menyerah."
K2 = 'Ia berkata, "Aku menyayangimu."'
K3 = "\"Coba jelaskan pengertian 'cross-validation' dalam Machine Learning!\""
K4 = "Surat keputusan itu bernomor 62/UN.34/19/2023."

print(K1)
print(K2)
print(K3)
print(K4)