# -*- coding: utf-8 -*-
"""02_Menampilkan kalimat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1SofaLNYPGc0VK5rwxuOQAMJSiba8bI
"""

# Program 2 - Membuat objek string Kata1 sampai Kata4

Kata1 = "Saya tak 'kan menyerah."
Kata2 = 'Ia berkata, "Aku menyayangimu."'
Kata3 = "\"Coba jelaskan pengertian 'cross-validation' dalam Machine Learning!\""
Kata4 = "Surat keputusan itu bernomor 62/UN.34/19/2023."

print(Kata1)
print(Kata2)
print(Kata3)
print(Kata4)
