# -*- coding: utf-8 -*-
"""03_akar_kuadrat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZEHyuYPgEEtMT4kZF2BFOe5pG0qy4IW
"""

import math

# Fungsi untuk menghitung akar persamaan kuadrat
def hitung_akar(data_koefisien):

    nilai_a, nilai_b, nilai_c = data_koefisien

    nilai_diskriminan = (nilai_b ** 2) - (4 * nilai_a * nilai_c)

    if nilai_diskriminan >= 0:

        akar_1 = (-nilai_b + math.sqrt(nilai_diskriminan)) / (2 * nilai_a)
        akar_2 = (-nilai_b - math.sqrt(nilai_diskriminan)) / (2 * nilai_a)

        print(f"Akar pertama = {akar_1:.3f}")
        print(f"Akar kedua   = {akar_2:.3f}")

    else:
        print("Persamaan memiliki akar imajiner")


# Input pengguna
nilai_a = float(input("Masukkan koefisien a : "))
nilai_b = float(input("Masukkan koefisien b : "))
nilai_c = float(input("Masukkan koefisien c : "))

# List
data_koefisien = [nilai_a, nilai_b, nilai_c]

# Pemanggilan fungsi
hitung_akar(data_koefisien)

import math

# Fungsi untuk menghitung akar persamaan kuadrat
def hitung_akar(data_koefisien):

    nilai_a, nilai_b, nilai_c = data_koefisien

    nilai_diskriminan = (nilai_b ** 2) - (4 * nilai_a * nilai_c)

    if nilai_diskriminan >= 0:

        akar_1 = (-nilai_b + math.sqrt(nilai_diskriminan)) / (2 * nilai_a)
        akar_2 = (-nilai_b - math.sqrt(nilai_diskriminan)) / (2 * nilai_a)

        print(f"Akar pertama = {akar_1:.3f}")
        print(f"Akar kedua   = {akar_2:.3f}")

    else:
        print("Persamaan memiliki akar imajiner")


# Input pengguna
nilai_a = float(input("Masukkan koefisien a : "))
nilai_b = float(input("Masukkan koefisien b : "))
nilai_c = float(input("Masukkan koefisien c : "))

# List
data_koefisien = [nilai_a, nilai_b, nilai_c]

# Pemanggilan fungsi
hitung_akar(data_koefisien)

import math

# Fungsi untuk menghitung akar persamaan kuadrat
def hitung_akar(data_koefisien):

    nilai_a, nilai_b, nilai_c = data_koefisien

    nilai_diskriminan = (nilai_b ** 2) - (4 * nilai_a * nilai_c)

    if nilai_diskriminan >= 0:

        akar_1 = (-nilai_b + math.sqrt(nilai_diskriminan)) / (2 * nilai_a)
        akar_2 = (-nilai_b - math.sqrt(nilai_diskriminan)) / (2 * nilai_a)

        print(f"Akar pertama = {akar_1:.3f}")
        print(f"Akar kedua   = {akar_2:.3f}")

    else:
        print("Persamaan memiliki akar imajiner")


# Input pengguna
nilai_a = float(input("Masukkan koefisien a : "))
nilai_b = float(input("Masukkan koefisien b : "))
nilai_c = float(input("Masukkan koefisien c : "))

# List
data_koefisien = [nilai_a, nilai_b, nilai_c]

# Pemanggilan fungsi
hitung_akar(data_koefisien)