# -*- coding: utf-8 -*-
"""Program 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTiIU79uUNn4BOp3cht5QJNMgEm0gpuy
"""

# Input NIP ASN
NIP = input("Masukkan NIP ASN: ")

# Mengambil tahun, bulan, dan tanggal lahir
Tahun = NIP[0:4]
Bulan = NIP[4:6]
Tanggal = NIP[6:8]

# Percabangan untuk nama bulan
if Bulan == "01":
    nama_bulan = "Januari"
elif Bulan == "02":
    nama_bulan = "Februari"
elif Bulan == "03":
    nama_bulan = "Maret"
elif Bulan == "04":
    nama_bulan = "April"
elif Bulan == "05":
    nama_bulan = "Mei"
elif Bulan == "06":
    nama_bulan = "Juni"
elif Bulan == "07":
    nama_bulan = "Juli"
elif Bulan == "08":
    nama_bulan = "Agustus"
elif Bulan == "09":
    nama_bulan = "September"
elif Bulan == "10":
    nama_bulan = "Oktober"
elif Bulan == "11":
    nama_bulan = "November"
elif Bulan == "12":
    nama_bulan = "Desember"

# Output
print("Tanggal Lahir ASN:", Tanggal, nama_bulan, Tahun)