# -*- coding: utf-8 -*-
"""Selamat Datang di Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import math

def hitung_jarak(x, y):
    return math.sqrt(
        (x[0] - y[0]) ** 2 +
        (x[1] - y[1]) ** 2 +
        (x[2] - y[2]) ** 2
    )

a = (2, 1, 3)
b = (1, -4, 6)
c = (-2, 3, -2)

try:
    x1 = float(input("Masukkan x1: "))
    x2 = float(input("Masukkan x2: "))
    x3 = float(input("Masukkan x3: "))

    titik_u = (x1, x2, x3)

    jarak_a = hitung_jarak(titik_u, a)
    jarak_b = hitung_jarak(titik_u, b)
    jarak_c = hitung_jarak(titik_u, c)

    if jarak_a < jarak_b and jarak_a < jarak_c:
        cluster = "A"
    elif jarak_b < jarak_a and jarak_b < jarak_c:
        cluster = "B"
    else:
        cluster = "C"

    print(f"Jarak ke Cluster A = {jarak_a:.3f}")
    print(f"Jarak ke Cluster B = {jarak_b:.3f}")
    print(f"Jarak ke Cluster C = {jarak_c:.3f}")
    print(f"Titik U termasuk Cluster {cluster}")

except ValueError:
    print("Input harus berupa angka.")