# -*- coding: utf-8 -*-
"""06_interval_proporsi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e0e6Ur6LBIzZWSNWDVRPo-A4mPi5P1px
"""

import math

def cari_nilai_kritis(tingkat_signifikansi):
    if tingkat_signifikansi == 0.10:
        return 1.645
    elif tingkat_signifikansi == 0.05:
        return 1.96
    else:
        return None

def hitung_batas_kesalahan(proporsi_sampel, nilai_kritis, ukuran_sampel):
    return nilai_kritis * math.sqrt(
        (proporsi_sampel * (1 - proporsi_sampel)) / ukuran_sampel
    )

def hitung_interval_kepercayaan(proporsi_sampel, tingkat_signifikansi, ukuran_sampel):

    if proporsi_sampel < 0 or proporsi_sampel > 1:
        return "Error: Nilai proporsi harus antara 0 dan 1."

    nilai_kritis = cari_nilai_kritis(tingkat_signifikansi)

    if nilai_kritis is None:
        return "Error: Tingkat signifikansi hanya boleh 0.10 atau 0.05."

    batas_kesalahan = hitung_batas_kesalahan(
        proporsi_sampel,
        nilai_kritis,
        ukuran_sampel
    )

    interval_minimum = proporsi_sampel - batas_kesalahan
    interval_maksimum = proporsi_sampel + batas_kesalahan

    return interval_minimum, interval_maksimum


# Program Utama
nilai_proporsi = float(input("Masukkan nilai proporsi sampel: "))
alpha_input = float(input("Masukkan tingkat signifikansi (0.10 atau 0.05): "))
jumlah_data = int(input("Masukkan ukuran sampel: "))

hasil_perhitungan = hitung_interval_kepercayaan(
    nilai_proporsi,
    alpha_input,
    jumlah_data
)

if isinstance(hasil_perhitungan, str):
    print(hasil_perhitungan)
else:
    batas_awal, batas_akhir = hasil_perhitungan
    print(
        f"Interval Kepercayaan = ({batas_awal:.4f}, {batas_akhir:.4f})"
    )

import math

def cari_nilai_kritis(tingkat_signifikansi):
    if tingkat_signifikansi == 0.10:
        return 1.645
    elif tingkat_signifikansi == 0.05:
        return 1.96
    else:
        return None

def hitung_batas_kesalahan(proporsi_sampel, nilai_kritis, ukuran_sampel):
    return nilai_kritis * math.sqrt(
        (proporsi_sampel * (1 - proporsi_sampel)) / ukuran_sampel
    )

def hitung_interval_kepercayaan(proporsi_sampel, tingkat_signifikansi, ukuran_sampel):

    if proporsi_sampel < 0 or proporsi_sampel > 1:
        return "Error: Nilai proporsi harus antara 0 dan 1."

    nilai_kritis = cari_nilai_kritis(tingkat_signifikansi)

    if nilai_kritis is None:
        return "Error: Tingkat signifikansi hanya boleh 0.10 atau 0.05."

    batas_kesalahan = hitung_batas_kesalahan(
        proporsi_sampel,
        nilai_kritis,
        ukuran_sampel
    )

    interval_minimum = proporsi_sampel - batas_kesalahan
    interval_maksimum = proporsi_sampel + batas_kesalahan

    return interval_minimum, interval_maksimum


# Program Utama
nilai_proporsi = float(input("Masukkan nilai proporsi sampel: "))
alpha_input = float(input("Masukkan tingkat signifikansi (0.10 atau 0.05): "))
jumlah_data = int(input("Masukkan ukuran sampel: "))

hasil_perhitungan = hitung_interval_kepercayaan(
    nilai_proporsi,
    alpha_input,
    jumlah_data
)

if isinstance(hasil_perhitungan, str):
    print(hasil_perhitungan)
else:
    batas_awal, batas_akhir = hasil_perhitungan
    print(
        f"Interval Kepercayaan = ({batas_awal:.4f}, {batas_akhir:.4f})"
    )

import math

def cari_nilai_kritis(tingkat_signifikansi):
    if tingkat_signifikansi == 0.10:
        return 1.645
    elif tingkat_signifikansi == 0.05:
        return 1.96
    else:
        return None

def hitung_batas_kesalahan(proporsi_sampel, nilai_kritis, ukuran_sampel):
    return nilai_kritis * math.sqrt(
        (proporsi_sampel * (1 - proporsi_sampel)) / ukuran_sampel
    )

def hitung_interval_kepercayaan(proporsi_sampel, tingkat_signifikansi, ukuran_sampel):

    if proporsi_sampel < 0 or proporsi_sampel > 1:
        return "Error: Nilai proporsi harus antara 0 dan 1."

    nilai_kritis = cari_nilai_kritis(tingkat_signifikansi)

    if nilai_kritis is None:
        return "Error: Tingkat signifikansi hanya boleh 0.10 atau 0.05."

    batas_kesalahan = hitung_batas_kesalahan(
        proporsi_sampel,
        nilai_kritis,
        ukuran_sampel
    )

    interval_minimum = proporsi_sampel - batas_kesalahan
    interval_maksimum = proporsi_sampel + batas_kesalahan

    return interval_minimum, interval_maksimum


# Program Utama
nilai_proporsi = float(input("Masukkan nilai proporsi sampel: "))
alpha_input = float(input("Masukkan tingkat signifikansi (0.10 atau 0.05): "))
jumlah_data = int(input("Masukkan ukuran sampel: "))

hasil_perhitungan = hitung_interval_kepercayaan(
    nilai_proporsi,
    alpha_input,
    jumlah_data
)

if isinstance(hasil_perhitungan, str):
    print(hasil_perhitungan)
else:
    batas_awal, batas_akhir = hasil_perhitungan
    print(
        f"Interval Kepercayaan = ({batas_awal:.4f}, {batas_akhir:.4f})"
    )